apiVersion: apps/v1
kind: Deployment
metadata:
  name: interceptor
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: interceptor
  template:
    metadata:
     labels:
       app.kubernetes.io/name: interceptor
    spec:
      serviceAccountName: default
      containers:
        - name: interceptor
          image: quay.io/kmcdermo/interceptor
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: interceptor
  namespace: default
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: interceptor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
